### PR TITLE
Signing as4

### PR DESCRIPTION
**Pull request by br0kk0l1**

### CODE REVIEW

**Review by ishifoev — APPROVED** [review]
We need to remove from invoice-ubl old files

**Review by ishifoev — APPROVED** [review]
Nice changes mate! But I think after some work needs to remove not need files from this PR!

**Comment by michielbdejong** [comment]
What is the status of this PR?

**Comment by ishifoev** [comment]
> What is the status of this PR?

I think Banz worked, with such updates for AS4 implementation.

**Comment by ishifoev** [comment]
@br0kk0l1 Banz How do you think need it for merge or you are working still for this problem?

**Pull request closed without merging**
